JCN 131 fix al selectear por flags
janis-commerce/query-builder pull request #5
Opened 2019-08-07 15:53 UTC by gastonpereyra

**JCN 131-FIX-AL-SELECTEAR-POR-FLAGS**
JCN-131 fix al selectear por flags

**LINK AL TICKET**

https://fizzmod.atlassian.net/browse/JCN-131

**DESCRIPCIÓN DEL REQUERIMIENTO**
5.1. Se requiere mejorar los filtros por flags, actualmente no esta tomando el valor obtenido en los filtros, sino que aplica siempre el valor de la flag declarada en el modelo
5.2. Se deberá poder filtrar por alguna flag, en donde el value pueda ser 1 y/o 0. ej WHERE (t.flags & 1) = 1) o WHERE (t.flags & 1) = 0)

**DESCRIPCIÓN DE LA SOLUCIÓN**
Se arregló el código donde no tomaba el valor correcto.

2019-08-07 16:30 UTC, jormaechea commented
@gastonpereyra ojo que cayó el coverage porqe faltaron flags para el código que modificaste..

2019-08-07 19:21 UTC, manuelvilche approved these changes

2019-08-08 14:59 UTC, jormaechea requested changes

2019-08-08 14:59 UTC, jormaechea commented on lib/query-builder-filters.js
> +			value = ['string', 'number', 'boolean'].includes(typeof value) ? value : QueryBuilderFields._getFlagData(fieldName).value;
Che, `_getFlagData()` recibe un string. Y nunca va a llegarle, porque no entra al else.. Puede ser que no tenga sentido o hay algo que no estoy viendo? :thinking:

2019-08-08 14:59 UTC, jormaechea commented on lib/query-builder-filters.js
> +			value = ['string', 'number', 'boolean'].includes(typeof value) ? value : QueryBuilderFields._getFlagData(fieldName).value;
De alguna manera los test entran, asique no sé, no estoy entendiendo algo creo..

2019-08-08 14:59 UTC, jormaechea commented on lib/query-builder-filters.js
> +			value = ['string', 'number', 'boolean'].includes(typeof value) ? value : QueryBuilderFields._getFlagData(fieldName).value;
@gastonpereyra Ahí estuvimos viendo con Manu. Lo que tiene que pasar en realidad, es que si te mandan algún valor que deba ser considerado como `false` (`0, false, '0', 'false') se debe filtrar con el valor `0`. En cualquier otro caso, se debe filtrar con el valor de la flag.

Con este cambio debería estar OK:

```suggestion
			value = !value || value === '0' || value === 'false' ? 0 : QueryBuilderFields._getFlagData(fieldName).value;
```

2019-08-08 14:59 UTC, jormaechea commented on tests/query-builder-filters-test.js
> +				filters: { isActive: 0, error: 0 }
Acá la prueba real es mandar `0`, `'0'`, `'false'`.

2019-08-08 18:21 UTC, jormaechea approved these changes
:+1:

2019-08-08 18:24 UTC, merged